[tool.briefcase]
project_name = "Noelle Calculator"
bundle = "ys.noelle"
version = "0.0.1"
url = "https://github.com/Timmhxw/Noelle_Calculator"
license = "BSD license"
author = 'Timmyhxw'
author_email = "timmyhxw@noelle.ys"

[tool.briefcase.app.noellecalculator]
formal_name = "Noelle Calculator"
description = "A simple calculator"
icon = "src/noellecalculator/resources/noellecalculator"
sources = ['src/noellecalculator','include']
requires = [
    
]


[tool.briefcase.app.noellecalculator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.noellecalculator.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.noellecalculator.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.noellecalculator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.noellecalculator.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
